#pragma once

#define DISPLAY_COLOR_MOD_ACTIVE       0xb1e5f0
#define DISPLAY_COLOR_MOD_INACTIVE     0x3b527c
#define DISPLAY_COLOR_MOD_SEPARATOR    0x606060
#define DISPLAY_COLOR_MOD_CAPS_WORD    0xffbf00

#define DISPLAY_COLOR_WPM_BAR_ACTIVE   0xc8a2c8
#define DISPLAY_COLOR_WPM_BAR_INACTIVE 0x242424
#define DISPLAY_COLOR_WPM_TEXT         0xc8a2c8

#define DISPLAY_COLOR_LAYER_TEXT       0xffffff
#define DISPLAY_COLOR_LAYER_DOT_ACTIVE   0xe0e0e0
#define DISPLAY_COLOR_LAYER_DOT_INACTIVE 0x575757

// Battery tiers by level: HIGH >60% (light blue), MID 30-60% (pastel yellow),
// LOW <30% (red, reused from the old WPM colour). FILL = arc indicator + label
// box; RING = the dim arc track behind it.
#define DISPLAY_COLOR_BATTERY_FILL     0xa8d0e6   // HIGH  light blue
#define DISPLAY_COLOR_BATTERY_RING     0x32424d
#define DISPLAY_COLOR_BATTERY_BG       0x505050
#define DISPLAY_COLOR_BATTERY_LABEL    0xffffff

#define DISPLAY_COLOR_BATTERY_DISCONNECTED_FILL  0x383c42
#define DISPLAY_COLOR_BATTERY_DISCONNECTED_RING  0x282c30
#define DISPLAY_COLOR_BATTERY_DISCONNECTED_LABEL 0x000000

#define DISPLAY_COLOR_BATTERY_MID_FILL  0xf5e08c   // MID  pastel yellow
#define DISPLAY_COLOR_BATTERY_MID_RING  0x4a4530

#define DISPLAY_COLOR_BATTERY_LOW_FILL  0xc2526a   // LOW  red
#define DISPLAY_COLOR_BATTERY_LOW_RING  0x4a2730

#define DISPLAY_COLOR_USB_ACTIVE_BG        0xb9b9a7
#define DISPLAY_COLOR_USB_INACTIVE_BG      0x4F4F40
#define DISPLAY_COLOR_BLE_ACTIVE_BG        0x569FA7
#define DISPLAY_COLOR_BLE_INACTIVE_BG      0x353f40
#define DISPLAY_COLOR_OUTPUT_ACTIVE_TEXT   0x000000
#define DISPLAY_COLOR_OUTPUT_INACTIVE_TEXT 0x7b7d93

#define DISPLAY_COLOR_SLOT_ACTIVE_BG   0x7b7d93
#define DISPLAY_COLOR_SLOT_INACTIVE_BG 0x353640
#define DISPLAY_COLOR_SLOT_TEXT        0xffffff
